@host = http://localhost:3000
@jwt = eyJhbGciOiJIUzI1NiJ9.eyJzdHVkZW50X2lkIjo1LCJleHAiOjE2MzU0MzI2ODR9.oUnu7o6-ANQfYpTPDQCbx_Lj0KBGgeRg5MdAYgoe3MI 



### SKILL INDEX
  get http://localhost:3000/skills
  Authorization: Bearer {{jwt}}

### SKILL SHOW
  get http://localhost:3000/skills/2
  Authorization: Bearer {{jwt}}
### SKILL CREATE

  post http://localhost:3000/skills.json
  Content-Type: application/json
  Authorization: Bearer {{jwt}}

  {
  "skill_name": "Typing"
  }

### SKILL UPDATE
  patch http://localhost:3000/skills/6
  Authorization: Bearer {{jwt}}
  Content-Type: application/json

  {
  "skill_name": "Typing really fast"
  }
### SKILL DESTROY
  delete http://localhost:3000/skills/6
  Authorization: Bearer {{jwt}}

### EXPERIENCE INDEX
  GET {{host}}/experiences.json
### EXPERIENCE SHOW
  get {{host}}/experiences/1.json
### EXPERIENCE CREATE
  POST {{host}}/experiences.json
  Content-Type: application/json
  Authorization: Bearer {{jwt}}

  {
    "start_date": "2000-01-01",
    "end_date": "2004-01-01",
    "job_title": "Singer",
    "company_name": "Test",
    "detais": "N/A"
  }
  
### EXPERIENCE UPDATE
  PATCH http://localhost:3000/experiences/8.json
  Authorization: Bearer {{jwt}}
  Content-Type: application/json

  {
  "job_title": "A New Job Title",
  "company_name": "This is a better company"
  }

### EXPERIENCE DELETE
  DELETE http://localhost:3000/experiences/8.json
  Content-Type: application/json
  Authorization: Bearer {{jwt}}


### EDUCATION INDEX
  GET {{host}}/educations.json

### EDUCATION SHOW
  GET {{host}}/educations/1.json

### EDUCATION CREATE
  POST http://localhost:3000/educations.json
  Content-Type: application/json
  Authorization: Bearer {{jwt}}

  {
  "start_date": "2000-06-01",
  "end_date": "2000-10-01",
  "degree": "Fake Degree4",
  "university_name": "Test University5",
  "details": "Current User Test"

  }

### EDUCATION UPDATE
  PATCH http://localhost:3000/educations/8
  Authorization: Bearer {{jwt}}
  Content-Type: application/json

  {
  "degree": "Best degree",
  "university_name": "Test"
  }

### EDUCATION DELETE
  DELETE http://localhost:3000/educations/8.json
  Content-Type: application/json
  Authorization: Bearer {{jwt}}




### SESSIONS CREATE
  POST {{host}}/sessions.json
  Content-Type: application/json

  {
  "email": "test3",
  "password": "test3"
  }


### STUDENTS INDEX
  GET {{host}}/students
### STUDENTS SHOW
  GET {{host}}/students/2.json


### STUDENTS CREATE

  POST {{host}}/students.json
  Content-Type: application/json

  {
  "first_name": "test4",
  "last_name": "test4",
  "email": "test4",
  "password": "test4",
  "short_bio": "test4",
  "linkedin_url": "test4",
  "twitter_handle": "test4",
  "personal_blog": "test2",
  "online_resume_url": "test2",
  "github_url": "test2",
  "photo": "test",
  "phone_number" : "test"
  }


### STUDENTS UPDATE
  PATCH {{host}}/students/7.json
  Content-Type: application/json
  Authorization: Bearer {{jwt}}


  {
  "first_name": "David"
  }
### STUDENTS DELETE
  DELETE {{host}}/students/7.json
  Authorization: Bearer {{jwt}}


### PROJECT INDEX
  get http://localhost:3000/projects
  Authorization: Bearer {{jwt}}
### PROJECT SHOW
  get http://localhost:3000/projects/2
### PROJECT CREATE
  post http://localhost:3000/projects.json
  Content-Type: application/json
  Authorization: Bearer {{jwt}}

  {
  "name": "newProject2",
  "description": "learned some stuff",
  "screenshot": "dfsafasdf",
  "url": "dfaasdfadsfas"
  }
### PROJECT UPDATE
  patch http://localhost:3000/projects/4
  Authorization: Bearer {{jwt}}
  Content-Type: application/json
  
  { 
  "name": "updatedNewProject",
  "description": "learned some stuff about computers",
  "screnshot": "updatedNewProject.screenshot",
  "url": "updatedNewProject.url"
  }
### PROJECT DESTROY
  delete http://localhost:3000/projects/4
  Authorization: Bearer {{jwt}}